In [1]:
1+1

2

In [4]:
2*3
4*5

20

In [10]:
print("1+1 =", 1+1)

1+1 = 2


In [11]:
print("2*2 =", 2*2)

2*2 = 4


In [12]:
print("3:3 =", 3/3)

3:3 = 1.0


In [3]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.metrics import confusion_matrix

In [6]:
np.ndarray

numpy.ndarray

In [7]:
np.array

<function numpy.array>

In [49]:
x = [12, 3, 6, 14]
print("# lists have commas between attibutes")
print(x)
print("type: ", type(x))

# lists have commas between attibutes
[12, 3, 6, 14]
type:  <class 'list'>


In [53]:
print("x[0]: ",x[0])
print()
print("# negative index picks the item from the end of the array")
print("x[-1]:", x[-1])

x[0]:  12

# negative index picks the item from the end of the array
x[-1]: 14


In [41]:
x = np.array([12, 3, 6, 14])
print("x: ", x)
print("type:", type(x))
print()
print("# dimension of the array")
print("x.ndim: ", x.ndim)
print()
print("# size of the array")
print("x.shape: ", x.shape)
print()
print("# first item in the array")
print(x[0])

x:  [12  3  6 14]
type: <class 'numpy.ndarray'>

# dimension of the array
x.ndim:  1

# size of the array
x.shape:  (4,)

# first item in the array
12


In [42]:
x = np.array([ [1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12] ])
print("# arrays do not have commas when printed")
print("x.ndim: ", x.ndim)
print(x)
print()
print("First array, second position:", x[0,1])
print("Second array, second position:", x[1,2])
print("Third array, second position:", x[2,3])

# arrays do not have commas when printed
x.ndim:  2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First array, second position: 2
Second array, second position: 7
Third array, second position: 12


In [43]:
x = np.array([
 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[21, 22, 23, 24], [25, 26, 27, 28], [29, 30, 31, 32]]
 ])
print("Array Dimension: ", x.ndim)
print("Array: ")
print(x)
print()
print("# x[0,1,2] -> 0: first list, 1: second set, 2: third item")
print(x[0,1,2])

Array Dimension:  3
Array: 
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[21 22 23 24]
  [25 26 27 28]
  [29 30 31 32]]]

# x[0,1,2] -> 0: first list, 1: second set, 2: third item
7


In [61]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr)
print("Start from -> up to, not including")

# from 3rd element to 8th exclusive 
print("arr[3:8]:", arr[3:8])

# start, end (exclusive), step. From 3rd element, upto 8th exclusive in step of 2
print("arr[3:8:2]:", arr[3:8:2])

# from 3rd element, to the last element exclusive 
print("arr[3:-1]:", arr[3:-1])

# from 3 to the end of the array
print("arr[3:]:", arr[3:])

# from first element to 5th exclusive 
print("arr[:5]:", arr[:5])

[ 0  1  2  3  4  5  6  7  8  9 10]
Start from -> up to, not including
arr[3:8]: [3 4 5 6 7]
arr[3:8:2]: [3 5 7]
arr[3:-1]: [3 4 5 6 7 8 9]
arr[3:]: [ 3  4  5  6  7  8  9 10]
arr[:5]: [0 1 2 3 4]


In [62]:
new = arr[3:8]
print(new)

[3 4 5 6 7]


In [65]:
# slice of the array is the reference to the object
# if we change new array item, it will also change in the original array
new[0]=33
print(new)
print(arr[3:8])
# example of full array output
print("New Array: ", new)
print("Original Array: ", arr)

[33  4  5  6  7]
[33  4  5  6  7]
New Array:  [33  4  5  6  7]
Original Array:  [ 0  1  2 33  4  5  6  7  8  9 10]


In [67]:
# to get the copy of the array and not edit the orignal, array.copy needs to be used 
myarray = arr.copy()

print("myarray: ", myarray)
print("arr: ", arr)

myarray[3]=3

print("myarray: ", myarray)
print("arr: ", arr)

# now, the original array has not changed

myarray:  [ 0  1  2 33  4  5  6  7  8  9 10]
arr:  [ 0  1  2 33  4  5  6  7  8  9 10]
myarray:  [ 0  1  2  3  4  5  6  7  8  9 10]
arr:  [ 0  1  2 33  4  5  6  7  8  9 10]


In [80]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
print("arr: ", arr)
print()
b = arr.reshape(3, 4)
print("Reshaping to [3, 4], 3 columns 4 entries: ")
print(b)


arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaping to [3, 4], 3 columns 4 entries: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [81]:
print("arr: ", arr)
print()
b = arr.reshape(2, 2, 3)
print("Reshaping to [2, 2, 3], 2 lists, 2 columns, 3 items")
print(b)

arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaping to [2, 2, 3], 2 lists, 2 columns, 3 items
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [82]:
print("arr: ", arr)
print()

b = arr.reshape(2, 2, -1)

print("Reshaping to [2, 2, -1], 2 lists, 2 columns")
print(b)

arr:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaping to [2, 2, -1], 2 lists, 2 columns
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
