In [8]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

In [13]:
actual = [0, 1, 0, 1] 
predicted = [1, 1, 1, 0]

In [48]:
print("actual type:", type(actual))
print("predicted type:", type(predicted))
print("actual: ", actual, "\npredicted: ", predicted)

actual type: <class 'list'>
predicted type: <class 'list'>
actual:  [0, 1, 0, 1] 
predicted:  [1, 1, 1, 0]


In [11]:
cm = confusion_matrix(actual, predicted)
print("cm type:", type(cm))
print("\nConfusion Matrix:\n", cm)

cm type: <class 'numpy.ndarray'>

Confusion Matrix:
 [[0 2]
 [1 1]]


In [29]:
# ravel returns a flattened array in a row major style 
r = cm.ravel()
print("r type:", type(r))
tn, fp, fn, tp = cm.ravel()
print("TN", tn, "FP", fp, "FN", fn, "TP", tp)

r type: <class 'numpy.ndarray'>
TN 0 FP 2 FN 1 TP 1


In [49]:
actual2 = ['B', 'M', 'B', 'M'] 
predicted2 = ['M', 'M', 'M', 'B']
print("actual2: ", actual2, "\npredicted2: ", predicted2)

actual2:  ['B', 'M', 'B', 'M'] 
predicted2:  ['M', 'M', 'M', 'B']


In [18]:
cm2 = confusion_matrix(actual2, predicted2)
print("\nConfusion Matrix2:\n", cm2)
print()
r2 = cm2.ravel()
tn, fp, fn, tp = cm2.ravel()
print("TN", tn, "FP", fp, "FN", fn, "TP", tp)


Confusion Matrix2:
 [[0 2]
 [1 1]]

TN 0 FP 2 FN 1 TP 1


In [40]:
actual3 = ['W', 'M', 'W', 'M'] 
predicted3 = ['M', 'M', 'M', 'W']
print("actual3: ", actual3, "\npredicted3: ", predicted3)

actual3:  ['W', 'M', 'W', 'M'] 
predicted3:  ['M', 'M', 'M', 'W']


In [41]:
cm3 = confusion_matrix(actual3, predicted3, labels=["W", "M"])
print("\nConfusion Matrix3:\n", cm3)
print()
r3 = cm3.ravel()
tn, fp, fn, tp = cm3.ravel()
print("TN", tn, "FP", fp, "FN", fn, "TP", tp)


Confusion Matrix3:
 [[0 2]
 [1 1]]

TN 0 FP 2 FN 1 TP 1


In [26]:
actual4 = ["cat", "ant", "cat", "cat", "ant", "bird"] 
predicted4 = ["ant", "ant", "cat", "cat", "ant", "cat"]
print("actual4: ", actual4, "\npredicted4: ", predicted4)

actual4:  ['cat', 'ant', 'cat', 'cat', 'ant', 'bird'] 
predicted4:  ['ant', 'ant', 'cat', 'cat', 'ant', 'cat']


In [46]:
cm4 = confusion_matrix(actual4, predicted4, labels=["ant", "bird", "cat"])
print("\nConfusion Matrix4:\n", cm4)
print()


Confusion Matrix4:
 [[2 0 0]
 [0 0 1]
 [1 0 2]]



In [42]:
print()
actual5 = [ 'attack', 'normal', 'normal', 'attack', 'normal', 'normal', 'attack', 'normal', 'attack']
predicted5 = ['attack' , 'normal', 'attack', 'attack', 'normal', 'normal', 'normal', 'normal', 'normal']
print("actual5: ", actual5, "\npredicted4: ", predicted5)


actual5:  ['attack', 'normal', 'normal', 'attack', 'normal', 'normal', 'attack', 'normal', 'attack'] 
predicted4:  ['attack', 'normal', 'attack', 'attack', 'normal', 'normal', 'normal', 'normal', 'normal']


In [43]:
cm5 = confusion_matrix(actual5, predicted5, labels=["attack", "normal"])
print("\nConfusion Matrix5:\n", cm5)
print()


Confusion Matrix5:
 [[2 2]
 [1 4]]



In [44]:
r5 = cm5.ravel()
tn, fp, fn, tp = cm5.ravel()
print("TN", tn, "FP", fp, "FN", fn, "TP", tp)

TN 2 FP 2 FN 1 TP 4
