In [1]:
import pandas as pd
import numpy as np

In [3]:
1+1

2

In [2]:
df = pd.read_csv('data/iris.csv')

In [3]:
print("Type:", type(df), "\n")

Type: <class 'pandas.core.frame.DataFrame'> 



In [4]:
print("Head", "\n")
df.head()

Head 



sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [73]:
print("Columns:", df.columns, "\n")
print("Shape:", df.shape, "\n")

Columns: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object') 

Shape: (150, 5) 



In [26]:
# returns the table range
print("Index:", df.index, "\n")

Index: RangeIndex(start=0, stop=150, step=1) 



In [27]:
# returns the value of the row
print("Index a Row:", "\n", df.iloc[1], "\n")

Index a Row: 
 sepal_length       4.9
sepal_width        3.0
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object 



In [31]:
# get the value of row 1 column 1 
print("Value for row, column [1,1]:", df.iloc[1,1], "\n")


Value for row, column [1,1]: 3.0 



In [29]:
# prints the columns type
print("Column Type:", "\n", df.dtypes, "\n")

Column Type: 
 sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object 



In [32]:
# take the copy of the dataframe
df2 = df.copy()

In [34]:
print("df2 type:", type(df2))

df2 type: <class 'pandas.core.frame.DataFrame'>


In [50]:
print(df2)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [36]:
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [51]:
# set the value of an entry - locate the row to update
df2_row = df2.iloc[0]
print("Index[0]:", "\n", row_index)

Index[0]: 
 sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object


In [64]:
# update the row with new values
df2.at[0, 'species'] = "virginica"

In [67]:
df2_row = df2.iloc[0]
df_row = df.iloc[0]
print("df index[0]:", "\n", df_row, "\n")
print("df2 index[0]:", "\n", df2_row, "\n")

df index[0]: 
 sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object 

df2 index[0]: 
 sepal_length          5.1
sepal_width           3.5
petal_length          1.4
petal_width           0.2
species         virginica
Name: 0, dtype: object 



In [78]:
# X is the features, y is the target variable
X = df[["sepal_length","sepal_width","petal_length","petal_width"]]
y = df["species"]

# X is 150 entries and 4 columns
print(X.shape)
# y is 150 entries in 1 column
print(y.shape)

(150, 4)
(150,)


In [86]:
# below is better way
X = df.drop("species", axis=1)
y = df['species']

In [87]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [88]:
y.head()

0    setosa
1    setosa
2    setosa
3    setosa
4    setosa
Name: species, dtype: object

In [82]:
# Convert X and y to numpy arrays
X_array = X.to_numpy() # X.values 
y_array = y.to_numpy() # y.values

In [84]:
print(X_array)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [81]:
print(y_array)

['setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'versicolor' 'versicolor' 'v

In [91]:
print("X Type:", type(X))
print("X_array Type:", type(X_array))
print()
print("y Type:", type(y))
print("y_array Type:", type(y_array))

X Type: <class 'pandas.core.frame.DataFrame'>
X_array Type: <class 'numpy.ndarray'>

y Type: <class 'pandas.core.series.Series'>
y_array Type: <class 'numpy.ndarray'>


In [5]:
# print type for load_iris
print("Type:", type(df))

Type: <class 'pandas.core.frame.DataFrame'>


In [6]:
# import built in dataset
from sklearn.datasets import load_iris

In [7]:
# load iris database
iris = load_iris()

In [8]:
# Step 3: Convert the dataset into a DataFrame
df_iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [9]:
# print type 
print("Load_iris type:", type(df_iris))

Load_iris type: <class 'pandas.core.frame.DataFrame'>


In [11]:
print("Feature_names \n", iris.feature_names)
print("Target_names \n", iris.target_names)

Feature_names 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target_names 
 ['setosa' 'versicolor' 'virginica']


In [12]:
# Set X to be the iris data and y to be the iris target
X = iris.feature_names
y = iris.target_names

print(X)
print(y)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [14]:
# Print out the description (DESCR) of the dataset and read it.
print("Description: \n", iris.DESCR)   # DESCR is case sensitive

Description: 
 .. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ==

In [19]:
# Q7 Onehot Encoding 

# Load the mushroom dataset 
df_mushroom = pd.read_csv('data/mushrooms.csv')
print(type(df_mushroom))

<class 'pandas.core.frame.DataFrame'>


In [22]:
# Set X to be all columns except 'type'
X = df_mushroom.drop(columns=['type'])
print("X:\n", X)

X:
      cap_shape cap_surface cap_color bruises     odor gill_attachment  \
0       convex      smooth     brown     yes  pungent            free   
1       convex      smooth    yellow     yes   almond            free   
2         bell      smooth     white     yes    anise            free   
3       convex       scaly     white     yes  pungent            free   
4       convex      smooth      gray      no     none            free   
...        ...         ...       ...     ...      ...             ...   
8119   knobbed      smooth     brown      no     none        attached   
8120    convex      smooth     brown      no     none        attached   
8121      flat      smooth     brown      no     none        attached   
8122   knobbed       scaly     brown      no    fishy            free   
8123    convex      smooth     brown      no     none        attached   

     gill_spacing gill_size gill_color stalk_shape  ...  \
0           close    narrow      black   enlarging  ...   
1

In [ ]:

# Set y to be the 'type' column (target variable)
y = df_mushroom['type']
print("y:\n", y)

In [ ]:

# One-hot encode X
X = pd.get_dummies(X)